const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
const FETCH_MESSAGES_DELETE = 'FETCH_MESSAGES_DELETE';
const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

export {
    FETCH_MESSAGES_REQUEST,
    FETCH_MESSAGES_SUCCESS,
    FETCH_MESSAGES_FAILURE,
    FETCH_MESSAGES_DELETE
}